---
- hosts: sps
  become: yes
  tasks:
    - name: Install Apache web server
      apt:
        name: apache2
        state: latest
        update_cache: yes

    - name: Start and enable Apache
      service:
        name: apache2
        state: started
        enabled: yes

    - name: Create custom index.html
      copy:
        dest: /var/www/html/index.html
        content: |
          <!DOCTYPE html>
          <html>
          <head>
              <title>My Ansible Website</title>
          </head>
          <body>
              <h1>Hello from Ansible </h1>
              <p>This page is deployed using Ansible on AWS Ubuntu.</p>
          </body>
          </html>

